####################################### Library FE #######################################
library-fe:
  image:
    tag: "20260828_1826"
    pullPolicy: IfNotPresent
  # U dev okruzenju FE je javno dostupan preko NLB-a
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
####################################### Library BE #######################################
library-be:
  image:
    tag: "20260824_2023"
    pullPolicy: IfNotPresent
  config:
    DB_HOST: "library.cv2iyum6yswq.eu-central-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "librarydb"
  sealedSecret:
    enabled: true
    encryptedData:
      DB_USERNAME: AgBAQg16zkkG9qKYIsL+cLewKPxa8hsfT49tYpgDND25HYb8wk1b+VGucy9b6cOhE9gMbR/vZdOe8pRIAW2cJ5OHy2LjAwzEZTdCFoX5i1eHaHaLonHlLQLWU6elzaKdFB8Ka2iJ5X6lf7W/RFndENO8AkZWcAtC70Jsdb/iKbP1QLXT0bwEIw2yYMcupHld6zKohFIdv1Y9PylPGXYCbU91UhKqpgAvmzryz7+mrBSz2OcfF0x5PEgpAseIXxwpHyAmYyAoVzw1sf92X1b5yKkc5rluDLAaG9t6OQ2xMT2IiAzgzqgnc1Fu7zAsbY+5n2zvoYwaSnsH6Q5/AZ+5WD9WppioMnamtasFPlTvs8/9GqNfdeHgmfLeCFr5BIe5POs2OKko1tX5wxH6NIH4vR+j+u7dYYHL1qYp3I775woZYpfCRtqc4AB1g+37e10QWor4pBzjeKI3D4nQU3sYm4FptAJuUtU94oHlIJiT2zxgWWpTbueeSMiMfPDdu8uQ5hE/b+7If6iw2Xc3Z512l0t8SAggsSk/pbBzy0Eb21aljN1wtS3GkCBgPzBB98H8NA2CfUD+gziYWz2SaDos8SuVd3QNTtIqONzX1RCO14Bs96XFcfSqzkjBmGfOOnXlUA+QxjZ+f9xnKsHJurK9H3+3BW7T4r0bKwy7YghjaT4GFQ40FayYNRIxiybdnahyNhxMb4zncQ==
      DB_PASSWORD: AgBFO+hXOTqabb1ZaOlf5EtBJNHE2rMV+mskuYmbhzSsC612icfNVrX0FzWgyeUtUR+q/uQdHIVLD/o0qBPMVzhQDVSNGYOknapZNaecP9N1CS8sILNMBH4cZiHbSKSG24an0EZ4DgYZGllHSn9CdlW0/bVXMwGCf9zwwYnuaivARInk/hL84jD4Rl2QBQ4yjexa380+hAhfFMLckpeAH8eTlYRY6OHKRBwZ1+iOC4p7XeEDUUlHnaz6zVweoqKAXSSVgjcF5enOkPyeKcyNI5H5wJCNh6YobkbKYuok8T7HmlY+dWJPOV+ZAumc5qZOzOgiBga/zf30zSUIP4dIb6Wsm14PiCJE8v9Z13s5oR/yBYzSz53LKq/ESytgvVVtgx6/ODzhTAb4lPMxq1SiXF8haV3ibrmPjX8XBBBWUGLbn3HVrNqnN5LaCgZLaPexi9EPQm15Kkk9tPUIka5HzEFkNGhSMM4gZG+Lu68mxp2A98mudyYTcdRIKCvm/+EVoj9qt1Szsr96PSadzu8M6qftGjj6Zrk/jYTLketxNUpfZAAFBnSlbOBnnEm/JrYutTDjdqJ7zGjj0sRvTAHIzCYT7NndHvnOs+oGhKkQxAe8pva/J/BEEqhMnj3arxR7NsGemeNpoTdwNmNaxvJgtBUQWqvE6GjIh4IwcUft+PgcvkEnBS7vILIrJnXmUUHd6NqWh2w2Gcyu3PHnyQ==
