####################################### Library FE #######################################
library-fe:
  image:
    tag: "20260717_1429"
    pullPolicy: Always

  # U dev okruzenju FE je javno dostupan preko NLB-a
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

####################################### Library BE #######################################
library-be:
  image:
    tag: latest
    pullPolicy: Always

  config:
    DB_HOST: "library.cv2iyum6yswq.eu-central-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "librarydb"

  sealedSecret:
    enabled: true
    encryptedData:
      DB_USERNAME: AgBuPgxBtWI/w2+lzPgtbs8jaglt9+NxWsHVmRJ7EMwXpGuxlcLhc0XS48YpFK3NPm8TjgWUUnE8uRx4omY/saEtP50ai/0OE+Y67RsVE8LtdsD+p/x5E7/H9CAq8CX0MZoUWxK7ZJcEDVhNzZDBlecwGoYs9J594T8y51L16ioT3WWxeQBkNje/3VYrLfVnXOVu5BhCvYHmHG/Uz2QFXrpq/UWW6Xa1edILgPKLPj7+OtgU95Sez/Y4sA5axCjO1cYHGkOuxrCEkh96YU+eWtcQpQ4MzEyACG5RSd+WRawgp2iZ8IvPhhBEtoOEdohNvzbunUe1Vi4+3jQ2SfmGihESb3UupmKSz4JXfq7uPjbt4nMLmQ9bClXkuw1i/dBARYB0wJwXxnSHa1a9wXKKY5u20JByvv51QZLnUhv84TT4xeQeqVfJ13GOun3dHBb/eqdffWvs3K5XK9HMSrLRTxr7I+Qiuu5q7cI48ZK5WclbXkE6p4jlgylfJFFd24nIC6UXG8KI5u00HIZamygjwDQaRkR5C1Zn+Wju5P3OHUXr4deWWYfvpaOvexEDy7UoU1eMbETLNHUdftI/hsNuogy2yvEnkNRC2w348AI8UJ32nHTR8E7OePJ7vF/a0TG1+kuLP95MR9Ec1ImFD5W3tiU9zBQlRKYTP8R2fRoaWczGfXWJey2ER/zewPIp4rj03U2LwotmMw==
      DB_PASSWORD: AgCGfxiJ7VJ4eBP4/O72IDgqCSpWS8/Loo97KnTOAHe+7VJu0iY1yp4xBXC5eAcUENga+j7+LjQRqv8I4VQXDnWGJnma4nqjIljRuqog5Ti3I89PrZwxjWE78n6dnLINDanu7nh3t3nQSqRPnRUEAcD4m7I28Z95LPRN5chUxtDAF7tSTCh7W5SIJ1xclYL5IX/T6ga3jKzs8uRZwSqCChe+7Ob0/UECeQCq3GJ189N+Y5e4Cp6P8C1By1w8kDdldYnAMVMJ2ydYv++gExFSzPbbTegmM5qVDjldyKtr0E08cYToJiuN5HH4E4IA1p4UJYzJtFzpFjxJAYv4bT2YQjDbz2cM1QkhCUSUmBBJs3K+shPNxPV2RrAvjEToYKJBMm0ASrzjHB8rf0PLmOd9x62uuutxjzM9+TeJmVYadqg5RJgp0yAbcLO/FQXWqGGZOkKz6LW7JkaG0CYxw2+UYFzO3Ny21FaEFQ7M9tqDThO6HRp9Z9J90fNQZua3tODvRQBYDZ/sZOX20NAW3ibR2EcoBX7HteJHFCGlgQu7n6ecXF3HM6laiKz4ZiSjZZk6gcOmpTxUwhRmCCqIfTSqw7qYVUBOJk+2oIntwSYzw5X2XJvGriQBNe4EmEL7/fZYp96wLlBUPQZBl1lPPj0wP1VvKRA73JbedVi74dWcxIiw8q5i0bFyYJ+zV5FE9xR5Ro9crztKvHu+kcLm8Q==
