{{- $v := index .Values .Chart.Name }}
{{- if $v.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret # encryptedData moze da desifruje ISKLJUCIVO sealed-secrets kontroler u klasteru
metadata:
  name: {{ $v.sealedSecret.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  encryptedData:
    {{- range $key, $value := $v.sealedSecret.encryptedData }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    type: Opaque
    metadata:
      name: {{ $v.sealedSecret.name }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}
